### ISSUE TITLE
sciine status command

### ISSUE THREAD

**Issue by ipatch** [jdum/asciinema-scene#1]
running `sciine status` with just that command leaves my terminal/shell in state where the command never errors or returns a value (for lack of better words) i think i just running that command should reference the help command similar to how running `sciine status my.cast` will print and error message stating run the `sciine status -h` command for how to use the sub commands and flags.

**Comment by jdum** [comment]
You are right, commands like `status` or `show` expect some input from `sys.stdin`, and they block if nothing is received. I will fix that with a small timeout to keep both the feature to receive data from stdin by default, and not unnecessarily block empty commands

**Comment by jdum** [comment]
Hi, today version 0.7.1 should fix the problem...

**Comment by ipatch** [comment]
awesome dude. 👍

i'm gunna be AFK for the next 10 days or so. so, if you fixed it i'd say close the issue. and thanks again for making and releasing this. 🙏
